### ISSUE TITLE
Some Wikipedia articles spend a lot of time in the AABB tree

### ISSUE THREAD

**Issue by pcwalton** [glennw/webrender#32]
For some reason we spend a lot of time in:

`aabbtree::_$LT$impl$GT$::find_best_node::ha90e540da0edbf0bkjd`

on http://en.wikipedia.org/wiki/Spotted_hyena

**Comment by glennw** [comment]
I noticed on some wikipedia pages there is a single display item at coordinates (0,100000) or similar. This can result in quite a large AABB tree. I tried to make it only split nodes where there is geometry but you still get quite a deep tree in these cases. It's probably worth checking if the time is due to something like that, then we can work out how to improve that.

**Comment by glennw** [comment]
I believe this is resolved - I changed the AABB tree to generate nodes lazily, so that you don't end up with huge amounts of empty nodes in edge cases.
