### ISSUE TITLE
Poor batching on GitHub

### ISSUE THREAD

**Issue by pcwalton** [glennw/webrender#35]
http://github.com/servo/servo has 132 draw calls. Something is going wrong here.

**Comment by pcwalton** [comment]
This is because there's too much overlap. I'm not sure why we create separate batches when things overlap.

**Comment by pcwalton** [comment]
@glennw Could you explain why we need to create separate batches when things overlap? I see that commenting out the code that does that causes problems, but I'm not sure why.

**Comment by glennw** [comment]
It's because items that use alpha (for glyphs, masks, images etc) need to be submitted in paint order to render correctly if they overlap. The current code is breaking a lot of extra batches because I removed the opaque batching optimization temporarily while adding parallel batching, and because the overlap tests are super conservative at the moment. I'm going to fix both of those this week :)
